### ISSUE TITLE
feedback on latest penn_daq

### ISSUE THREAD

**Issue by noel-gagnon** [pennsnoplus/penn_daq#13]
VMON: 5Vref reads 6.336V & is "red", test = passed (DVM = 5.0V)
cmos_timing: iseta should be set to 0 (as per SNO), isetM are pretty low (should be a fail)
caldac: only see two colors
chinj: don't know how to interpret the graphs
set_ttot: should specify channel #, VSI should be fixed at 120 (SNO)
mem_test: why are the address test boxes all red?
ped & chinj: tac values all low??

**Comment by mastbaum** [comment]
comments on the web interface side:

> VMON: 5Vref reads 6.336V & is "red", test = passed (DVM = 5.0V)

The web page colors red anything 15% out of spec, but the DAQ decides whether it passes or fails overall. @bonventre, could you do this on the daq side and include a pass/fail with each voltage in the list instead?

> caldac: only see two colors

They're all there. ADCs 0, 2, and 3 are right on top of each other.

> set_ttot: should specify channel #, VSI should be fixed at 120 (SNO)

@bonventre: the "chips" dictionary needs a key "id" viz doc/schema.md

> mem_test: why are the address test boxes all red?

Fixed, had the pass/fail convention backwards. Now "address_test == true" is success.

**Comment by bonventre** [comment]
i just fixed mem_test the other way to match the convention of the other tests...
I think the info is there for vmon it's just not useful yet since i set all the upper limits to 99 and lower to -99.
I'll also check that I'm converting adc counts to voltage correctly, we can check with xl2 if it comes to it.

**Comment by mastbaum** [comment]
mem_test: the key name is ambiguous... rename to either "address_test_error" or "address_test_ok". @bonventre: you pick one.

vmon: I'll take out my 15% check and just use the boolean in the DB. can you change that key name to a nice, short "ok"?

**Comment by mastbaum** [comment]
vmon pass/fail for each voltage is now set by the daq. added channel numbers to set_ttot.
