### ISSUE TITLE
Penn_Daq Guide for Dummys 

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#14]
Hi guy, 

When the new issue of Penn_Daq for Dummy's is released please let me know. :D 

Errors. 

-we are getting segmentation fault while trying to run penn_daq
-we had a quick look at thePennDB sight and was wondering if we could get cell # for ped_run values.
-also in the PennDB sight, the second ped_run sed it was balanced, but if you look closely and compare the data, it appears that it was not balanced.

**Comment by mastbaum** [comment]
wrote documentation for the web interface (debugdb) -- see https://github.com/mastbaum/debugdb/wiki

@bonventre: this should become part of your penn_daq guide eventually.

**Comment by bonventre** [comment]
as far as the balanced ped run, the database needs a little more configuring before that will work right. At the moment, loading cbal, ttot, or zdisc values from the database doesnt work at all.

**Comment by bonventre** [comment]
ok balanced ped_runs should work now

**Comment by mastbaum** [comment]
added cell in cc294e495f09e384f41cbde62ef31b9df6b368d3

**Comment by 21esc12** [comment]
hi guys i found a problem with ped_run agene, if you check the data base on the second ped_run you will notes that the TAC RMS values are now around ~500 and considered good (sometimes), where we use to get 1800 - 2600 as good ?

Also after doing a final test there is a status indicator to weather the whole board failed or passed, and one board passed everything exept the first ped_run. I was just wondering if that should be consdured a board that passed?,as long as the board can be balanced and passes the second ped_run.
