### ISSUE TITLE
Endless Loop Error

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#16]
hi guys 

Slot 9, 10, 11,12 ,13,14, 15, has a end less loop while trying  to set ttot. i tried all slots with the same boards and some slots multiple times to make sure the problem did not happen by chance. below is an example of what happens and it just keeps looping.

SOFT_GT is set to source the pulser
Setting ttot for crate/board 12 9, target time 440
Fit channel 2 (RMP/VSI 143 120) Times:  530     490     460     460
Fit channel 4 (RMP/VSI 145 120) Times:  520     600     620     450
Fit channel 6 (RMP/VSI 145 120) Times:  500     550     500     450
Fit channel 0 (RMP/VSI 146 120) Times:  520     590     520     450
Fit channel 1 (RMP/VSI 146 120) Times:  560     530     480     450
Fit channel 5 (RMP/VSI 146 120) Times:  560     600     530     450
Fit channel 7 (RMP/VSI 147 120) Times:  540     580     550     450
Fit channel 3 (RMP/VSI 149 120) Times:  550     550     470     450
updating the database
Setting ttot for crate/board 12 9, target time 440
Fit channel 2 (RMP/VSI 143 120) Times:  520     490     460     470
Fit channel 0 (RMP/VSI 146 120) Times:  520     590     520     450
Fit channel 1 (RMP/VSI 146 120) Times:  560     530     480     450
Fit channel 5 (RMP/VSI 146 120) Times:  560     590     530     450
Fit channel 6 (RMP/VSI 146 120) Times:  500     550     500     450
Fit channel 4 (RMP/VSI 147 120) Times:  540     650     650     450
Fit channel 7 (RMP/VSI 147 120) Times:  540     580     540     450
Fit channel 3 (RMP/VSI 149 120) Times:  520     560     480     450
updating the database
Setting ttot for crate/board 12 9, target time 440
Fit channel 2 (RMP/VSI 143 120) Times:  520     490     460     460
Fit channel 4 (RMP/VSI 145 120) Times:  520     600     600     450

I also found a problem with ped_run agene, if you check the data base on the second ped_run you will notes that the TAC RMS values are now around ~500 and considered good (sometimes), where we use to get 1800 - 2600 as good ?

**Comment by 21esc12** [comment]
i just tried slot 9 and 10 and its still stuck in a loop

**Comment by bonventre** [comment]
I hadn't actually updated the code on crag1 - make sure to type "git pull" and remake penn_daq after any new commits. It should be ready to try now
