### ISSUE TITLE
Missing Test

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#17]
In the past we had some test that are not available right now (that i know): 

see_reflection  ------  (excellent test that would be nice to have)
Dac_sweep   --------  (useful for trouble shooting Dacs)
vthr    ------------------- (not sure what this related to at the moment, will have to talk with noel)

**Comment by mastbaum** [comment]
see_refl was added to the db in e3d373146e7e940fe3093f109823fb73bbb581a0. up to @bonventre to actually run them :)

**Comment by bonventre** [comment]
dac sweep added
