### ISSUE TITLE
Final Test Display 

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#18]
In a final test window of any board, the test are listed is a nice chronological order, but it seems it is missing one test in the list. Could it be added ?

Test Order:

Fec_test

vmon

cgt_test

ped_run

cbal or crate_cbal  <---- missing

ped_run

chinj_scan

set_ttot

get_ttot

disc_check

cmos_m-gtvalid

zdisc

mb_stability_test

fifo_test

cald_test

mem_test

**Comment by mastbaum** [comment]
either they're not getting run or the final_test id isn't getting set in the crate_cbal document. can you provide the final test ID (bottom of the final test page) for a final test where the crate_cbal is missing?
