### ISSUE TITLE
Test in Chronological Order

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#19]
In "all test" in the databace, can the list of each tests done be sorted by date in each test topic?,from chronological order. (in side each topic it seems like there is no order)

**Comment by mastbaum** [comment]
clicking "All Tests" on the main page gives you a list of all the different types of tests, listed alphabetically. i see on the pages like "All tests for Crate 12" though, there doesn't seem to be any order. i'll make them chronological.

**Comment by mastbaum** [comment]
closed by mastbaum/debugdb fe3f116f4fb0e3d761707d3b95bfdb7c6555584b
