### ISSUE TITLE
Debugging Log Book

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#20]
The debugging log book seemed to work  until i tried making a fake log to see if it worked "dsdd",  when i went back in  to edit the text there is a error, "404 - Not Found". I tried making a new entry and leave "dsdd" for now and when trying to save a new log there is  another error, {"error":"conflict","reason":"Document update conflict."}

**Comment by mastbaum** [comment]
was this in chrome or firefox? for me it works fine in chrome and not at all in firefox. i'm working on it, but if you have chrome, just use that for now.

**Comment by 21esc12** [comment]
Firefox,. 

K, thanks

**Comment by mastbaum** [comment]
It now works in Firefox, but doesn't redirect to the right page when you create a new entry or delete one. For now, if you navigate back to the log book (click the link at the top to get back to the main page), it should be usable.
