### ISSUE TITLE
Charge Injection

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#25]
In the charge injection test results, the graphs are zoomed in quite a bit, is it possible to have all charts scaled out to a fix scale so it is easier to compare with a fast  look.

Also for every channel the charge value go's from 0 -25, is it possible to get a bigger sample of  charges?

**Comment by bonventre** [comment]
the charge i believe goes in steps of 10, so from 0 to 250? I can make it have finer steps if you want
