### ISSUE TITLE
set_ttot errors

### ISSUE THREAD

**Issue by bonventre** [pennsnoplus/penn_daq#28]
there are now two kinds of error and the error is by channel (it is moved to the channel dictionary). error = 1 means that it maxed out the dacs but couldn't get ttot long enough. error = 2 means that tub triggers weren't showing up even when ttot was at its minimum.

Also get_ttot now has two kinds of errors too. error = 1 means that the gtvalid time was shorter than the target time. error = 2 means that it was seeing pedestals when all the channels were enabled but lost them when only that channel was enabled.

**Comment by mastbaum** [comment]
closed by mastbaum/debugdb/commit/52bd0f5af0b70121f01a232a31032909676c5eba
