### ISSUE TITLE
Vmon tweak  

### ISSUE THREAD

**Issue by 21esc12** [pennsnoplus/penn_daq#35]
Voltage Monitoring Test
Fri Jan 13 14:03:41 2012

all voltages where saturated high  but 4V and 4V ref, still displayed as good, if its ok can we bring the acceptable rang in closer to 4v on both 

thanks,
Cam

Document ID: 2764e4576e4d20a08de141c0e4b15f4a

**Comment by bonventre** [comment]
adjusted in new version
